spring:
  application:
    name: core
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      authentication-database: admin
      database: images
      auto-index-creation: true
server:
  port: 8222